import { USER_ROLE, type UserRole } from "@/db/types/user.type";

export const CREATE_DAILY_REPORT_ROLES: readonly UserRole[] = [
  USER_ROLE.FRONTEND_DEVELOPER,
  USER_ROLE.BACKEND_DEVELOPER,
  USER_ROLE.FULLSTACK_DEVELOPER,
  USER_ROLE.LEAD_FRONTEND,
  USER_ROLE.LEAD_BACKEND,
];

export const REVIEW_DAILY_REPORT_ROLES: readonly UserRole[] = [
  USER_ROLE.LEAD_FRONTEND,
  USER_ROLE.LEAD_BACKEND,
];

export const VIEW_DAILY_REPORT_ROLES: readonly UserRole[] = [
  USER_ROLE.FRONTEND_DEVELOPER,
  USER_ROLE.BACKEND_DEVELOPER,
  USER_ROLE.FULLSTACK_DEVELOPER,
  USER_ROLE.LEAD_FRONTEND,
  USER_ROLE.LEAD_BACKEND,
];
