import { USER_ROLE, UserRole } from "@/db/types/user.type";

export const CREATE_REQUEST_LEAVE_ROLES = [
  USER_ROLE.FRONTEND_DEVELOPER,
  USER_ROLE.BACKEND_DEVELOPER,
  USER_ROLE.FULLSTACK_DEVELOPER,
  USER_ROLE.LEAD_FRONTEND,
  USER_ROLE.LEAD_BACKEND,
] as const;

export const VIEW_REQUEST_LEAVE_ROLES = [
  USER_ROLE.FRONTEND_DEVELOPER,
  USER_ROLE.BACKEND_DEVELOPER,
  USER_ROLE.FULLSTACK_DEVELOPER,
  USER_ROLE.LEAD_FRONTEND,
  USER_ROLE.IT_MANAGER,
  USER_ROLE.LEAD_BACKEND,
] as const;

// export const REVIEW_REQUEST_LEAVE_ROLES: readonly UserRole[] = [
//   USER_ROLE.LEAD_FRONTEND,
//   USER_ROLE.LEAD_BACKEND,
//   USER_ROLE.PROJECT_MANAGER,
//   USER_ROLE.IT_MANAGER,
// ];

export const REVIEW_REQUEST_LEAVE_ROLES = [
  USER_ROLE.LEAD_FRONTEND,
  USER_ROLE.IT_MANAGER,
] as const;

export function getRequestLeaveApprovalLevel(role: UserRole): 1 | 2 | null {
  if (role === USER_ROLE.LEAD_FRONTEND) {
    return 1;
  }

  if (role === USER_ROLE.IT_MANAGER) {
    return 2;
  }

  return null;
}
